import { createElement } from '@lwc/engine-dom';
import Tareas_Completadas_LWC from 'c/tareas_Completadas_LWC';

describe('c-tareas-completadas-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-tareas-completadas-lwc', {
            is: Tareas_Completadas_LWC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});